[package]
name = "akinator-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
lazy_static = "1.4"
reqwest = { version = "0.11", features = ["blocking"] }